INFO 2023-03-24 14:21:49,885 [main.py:captureLog:64] Connecting to device xe1
INFO 2023-03-24 14:21:50,023 [main.py:captureLog:64] Connecting to device xe2
INFO 2023-03-24 14:21:50,228 [main.py:captureLog:64] Connecting to device xe3
INFO 2023-03-24 14:21:50,497 [main.py:captureLog:64] Connecting to device xr1
INFO 2023-03-24 14:21:50,661 [main.py:captureLog:64] Connecting to device xr2
INFO 2023-03-24 14:21:50,923 [main.py:captureLog:64] Connecting to device xr3
INFO 2023-03-24 14:21:53,091 [main.py:captureLogX:41] ---getting capture logging from device xe2---
INFO 2023-03-24 14:21:53,436 [main.py:captureLogX:41] ---getting capture logging from device xe1---
INFO 2023-03-24 14:21:53,527 [main.py:captureLogX:41] ---getting capture logging from device xe3---
INFO 2023-03-24 14:21:54,664 [main.py:captureLogX:47] xe2_24-03-23_14_21_53.txt
INFO 2023-03-24 14:21:54,977 [main.py:captureLogX:47] xe1_24-03-23_14_21_53.txt
INFO 2023-03-24 14:21:55,044 [main.py:captureLogX:47] xe3_24-03-23_14_21_54.txt
ERROR 2023-03-24 14:22:02,065 [main.py:captureLogX:55] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-03-24 14:22:02,344 [main.py:captureLogX:55] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-03-24 14:22:23,331 [main.py:captureLogX:55] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-03-24 14:22:23,336 [main.py:captureLog:73] Get Logging Device - execution completed successfully.
INFO 2023-03-24 14:24:51,461 [main.py:captureLog:64] Connecting to device xe1
INFO 2023-03-24 14:24:51,590 [main.py:captureLog:64] Connecting to device xe2
INFO 2023-03-24 14:24:51,741 [main.py:captureLog:64] Connecting to device xe3
INFO 2023-03-24 14:24:51,871 [main.py:captureLog:64] Connecting to device xr1
INFO 2023-03-24 14:24:52,290 [main.py:captureLog:64] Connecting to device xr2
INFO 2023-03-24 14:24:52,563 [main.py:captureLog:64] Connecting to device xr3
INFO 2023-03-24 14:24:54,800 [main.py:captureLogX:41] ---getting capture logging from device xe1---
INFO 2023-03-24 14:24:54,825 [main.py:captureLogX:41] ---getting capture logging from device xe3---
INFO 2023-03-24 14:24:54,825 [main.py:captureLogX:41] ---getting capture logging from device xe2---
INFO 2023-03-24 14:24:55,912 [main.py:captureLogX:47] xe3_24-03-23_14_24_54.txt
INFO 2023-03-24 14:24:56,026 [main.py:captureLogX:47] xe2_24-03-23_14_24_54.txt
INFO 2023-03-24 14:24:56,030 [main.py:captureLogX:47] xe1_24-03-23_14_24_54.txt
INFO 2023-03-24 14:24:58,325 [main.py:captureLogX:41] ---getting capture logging from device xr1---
INFO 2023-03-24 14:24:59,392 [main.py:captureLogX:47] xr1_24-03-23_14_24_58.txt
ERROR 2023-03-24 14:25:03,955 [main.py:captureLogX:55] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-03-24 14:25:25,030 [main.py:captureLogX:55] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-03-24 14:25:25,035 [main.py:captureLog:73] Get Logging Device - execution completed successfully.
